### ISSUE TITLE
vector drawable doesn't expand to take the size specified

### ISSUE THREAD

**Issue by sudansh** [a-tolstykh/textview-rich-drawable#4]
if the compoundDrawableHeight/compoundDrawableWidth is greater than the vector's size it doesn't stretch to occupy the full height and width

**Comment by a-tolstykh** [comment]
Hello, @sudansh. Thanks for your report.
I will check the possibility to add this feature and will get to you back.

**Comment by a-tolstykh** [comment]
Fixed in 0.3.0 release.
