### ISSUE TITLE
EditText extension

### ISSUE THREAD

**Issue by DummyCo** [a-tolstykh/textview-rich-drawable#5]
It would be nice to have such EditText inheritor extension also, since it's in the same TextView hierarchy, thank you.

**Comment by a-tolstykh** [comment]
Hello @DummyCo, I also think that EditText extension will be useful. I was also thinking about Button/CheckBox and other TextView inheritors. I will plan this enhancement and add it to future releases. Thanks for a feedback.

**Comment by a-tolstykh** [comment]
Implemented in 0.3.0 release.
